* Text Excel
** What is this?
This is a program called Text Excel, which is a text based spreadsheet application I wrote in my Sophomore year of High School as part of my AP Computer Science A course.
** How do I run this program?
The main method is in TextExcel.java. Compile this program like you would any other java program. Though it was orginally writen using JDK 8, it has been shown to work with more recent JDKs.
** What does it do?
Text Excel is a very rudimentary program. When you run the program you will get a print out of the spreadsheet. From there, you can type in commands into your terminal and various things will happen. You can exit the program by typing quit If the program doesn't understand the command you have typed it will usually just do nothing, however, in some rare cases, it might crash.
** How do I close the program?
Use the command quit.
** How do I use this program?
First, before you can truely understand Text Excel, you must know that there are number of different cell types it has, which each behave differently.
*** Text Cells
These are cells that store text. To assign text to a cell, use the following command:
#+begin_src
A1 = "foo"
#+end_src
N.B. Quotes are required.\\

When displayed in the sheet, the contents are truncated if they are longer 10 letter or longer. The full contents are never lost and can be retrieved by typing the cell's name as a single command.
*** Value Cells
These cells store real numbers. To assign a number to a cell use the following command:
#+begin_src
A1 = 3.1415
#+end_src
*** Formula Cells:
These cells store formulas. When displayed in the sheet, these cells will either show the value the formula evaluates too, or #ERROR, if there was a divide by zero error, you tried to reference a non-number cell, or there was a cyclical dependency error. To assign a formula to a cell use the following command:
#+begin_src
A1 = ( 1 + 3.4 )
#+end_src
Text Excel requires the parenthesis before and after the formula, as well as spaces between every single token, or it will not be able to understand your request.\\

Formula Cells follow standard mathematical rules of precedence and only support the following: +, -, /, *, (, ), and cell references. For example, the following is allowed:
#+begin_src
A1 = 3
B1 = ( A1 * ( 2 + A1 ) )
#+end_src
After this, B1 would evaluate to 15.\\

Formulas also support taking the sum or average of a range, like so:
#+begin_src
A1 = 3
A2 = 4
A3 = 5
B2 = SUM A1-A3 + AVG A1-A3
#+end_src
Note that there should be no spaces before or after the dash in ranges
** Other commands
*** Clearing the sheet
#+begin_src
clear A1 // clear a single cell
clear // clear the entire sheet
#+end_src
*** Working with history
#+begin_src
history start n // starts recording commands, and will save only the last n
history display // displays all the recorded commands, with the earliest at the top of the list
history clear n // removes the n most recent commands from the history
history stop // stop recording history
#+end_src
*** Sort a region
#+begin_src
sorta A1-B3 // sort the range ascending
sortd A1-B3 // sort the range descending
#+end_src
Note that there should be no spaces before or after the dash in ranges.\\

When sorting, cells evaluating to numbers are considered "large" than text cells, which are considered "larger" than blank cells.
